# Generated by Django 4.2.10 on 2026-03-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_register', 'User Register'), ('user_update', 'User Update'), ('telegram_link', 'Telegram Link'), ('campaign_create', 'Campaign Create'), ('campaign_update', 'Campaign Update'), ('campaign_join', 'Campaign Join'), ('campaign_leave', 'Campaign Leave'), ('task_create', 'Task Create'), ('task_update', 'Task Update'), ('task_assign', 'Task Assign'), ('task_complete', 'Task Complete'), ('task_verify', 'Task Verify'), ('twitter_post', 'Twitter Post'), ('twitter_retweet', 'Twitter Retweet'), ('twitter_like', 'Twitter Like'), ('telegram_message', 'Telegram Message'), ('telegram_command', 'Telegram Command')], help_text='Type of action performed', max_length=50),
        ),
    ]
