# Generated by Django 4.2.10 on 2026-03-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Campaign name', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the campaign')),
                ('short_description', models.CharField(help_text='Short description for listings', max_length=500)),
                ('campaign_type', models.CharField(choices=[('regular', 'Regular Campaign'), ('twitter_storm', 'Twitter Storm'), ('hybrid', 'Hybrid (Regular + Twitter Storm)')], default='regular', help_text='Type of campaign', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', help_text='Current status of the campaign', max_length=20)),
                ('target_members', models.IntegerField(default=0, help_text='Target number of core members')),
                ('target_activities', models.IntegerField(default=0, help_text='Target number of activities')),
                ('target_twitter_posts', models.IntegerField(default=0, help_text='Target number of Twitter posts (for Twitter storms)')),
                ('twitter_hashtags', models.CharField(blank=True, help_text='Comma-separated list of hashtags for Twitter storm', max_length=500)),
                ('twitter_accounts', models.CharField(blank=True, help_text='Comma-separated list of Twitter accounts to mention', max_length=500)),
                ('twitter_storm_schedule', models.JSONField(blank=True, help_text='Schedule for Twitter storm activities', null=True)),
                ('telegram_channel_id', models.BigIntegerField(blank=True, help_text='Telegram channel ID for campaign announcements', null=True)),
                ('telegram_group_id', models.BigIntegerField(blank=True, help_text='Telegram group ID for campaign coordination', null=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='Planned start date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Planned end date', null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, help_text='Actual start date', null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, help_text='Actual end date', null=True)),
                ('current_members', models.IntegerField(default=0, help_text='Current number of core members')),
                ('completed_activities', models.IntegerField(default=0, help_text='Number of completed activities')),
                ('completed_twitter_posts', models.IntegerField(default=0, help_text='Number of completed Twitter posts')),
                ('total_points_awarded', models.IntegerField(default=0, help_text='Total points awarded in this campaign')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('sent_to_telegram', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Campaign Update',
                'verbose_name_plural': 'Campaign Updates',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignVolunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('banned', 'Banned')], default='pending', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Volunteer',
                'verbose_name_plural': 'Campaign Volunteers',
            },
        ),
    ]
