# Generated by Django 4.2.10 on 2026-03-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_add_multilingual_task_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Detailed task description (English)'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('twitter_post', 'Twitter Post'), ('twitter_retweet', 'Twitter Retweet'), ('twitter_comment', 'Twitter Comment'), ('twitter_like', 'Twitter Like'), ('telegram_share', 'Telegram Share'), ('telegram_invite', 'Telegram Invite'), ('content_creation', 'Content Creation'), ('petition', 'Petition'), ('mass_email', 'Mass Email'), ('research', 'Research'), ('other', 'Other')], help_text='Type of task', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Task title (English)', max_length=200),
        ),
    ]
