# Generated by Django 4.2.10 on 2026-03-12 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('campaigns', '0003_add_multilingual_campaign_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignvolunteer',
            name='group_invite_sent',
            field=models.BooleanField(default=False, help_text='Whether this volunteer has been sent a coordination group invite'),
        ),
        migrations.AddField(
            model_name='campaignvolunteer',
            name='invited_by',
            field=models.ForeignKey(blank=True, help_text='User who invited this volunteer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(help_text='Campaign name (English)', max_length=200),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='short_description',
            field=models.CharField(help_text='Short description for listings (English)', max_length=500),
        ),
        migrations.CreateModel(
            name='TwitterStorm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Storm title, e.g. "Operation Ceasefire Storm #1"', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description and context for volunteers')),
                ('scheduled_at', models.DateTimeField(help_text='The T-zero moment — when everyone posts')),
                ('duration_minutes', models.IntegerField(default=30, help_text='Storm duration in minutes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('countdown', 'Countdown Active'), ('active', 'Storm Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', help_text='Current storm status', max_length=20)),
                ('tweet_templates', models.JSONField(default=list, help_text='List of tweet template strings for volunteers')),
                ('hashtags', models.CharField(blank=True, help_text='Hashtags for this storm (overrides campaign defaults if set)', max_length=500)),
                ('mentions', models.CharField(blank=True, help_text='Target accounts to mention', max_length=500)),
                ('notify_1h', models.BooleanField(default=True, help_text='Send notification 1 hour before')),
                ('notify_15m', models.BooleanField(default=True, help_text='Send notification 15 minutes before')),
                ('notify_5m', models.BooleanField(default=True, help_text='Send notification 5 minutes before')),
                ('celery_task_ids', models.JSONField(blank=True, default=list, help_text='Stored Celery task IDs for countdown notifications')),
                ('participants_notified', models.IntegerField(default=0, help_text='Number of volunteers notified')),
                ('tweets_posted', models.IntegerField(default=0, help_text='Number of confirmed tweets posted')),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(help_text='Campaign this storm belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='storms', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(help_text='Manager who scheduled this storm', on_delete=django.db.models.deletion.CASCADE, related_name='created_storms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Twitter Storm',
                'verbose_name_plural': 'Twitter Storms',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='StormParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('notified', 'Notified'), ('ready', 'Ready'), ('posted', 'Posted'), ('verified', 'Verified')], default='notified', max_length=20)),
                ('tweet_text', models.TextField(blank=True, help_text='The actual tweet text posted')),
                ('tweet_url', models.URLField(blank=True, help_text='URL of the posted tweet')),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('storm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='campaigns.twitterstorm')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storm_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Storm Participant',
                'verbose_name_plural': 'Storm Participants',
            },
        ),
        migrations.CreateModel(
            name='ChannelPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('task_completion', 'Task Completion'), ('volunteer_joined', 'Volunteer Joined'), ('milestone', 'Milestone'), ('digest', 'Daily Digest'), ('campaign_update', 'Campaign Update'), ('recycle', 'Recycled Post')], help_text='Type of channel post', max_length=30)),
                ('message_text', models.TextField(help_text='The message text that was posted')),
                ('proof_url', models.URLField(blank=True, default='', help_text='Proof URL if task completion type')),
                ('telegram_message_id', models.BigIntegerField(blank=True, help_text='Telegram message ID for tracking reposts', null=True)),
                ('repost_count', models.IntegerField(default=0, help_text='Number of times this post has been recycled')),
                ('last_reposted_at', models.DateTimeField(blank=True, help_text='Last time this post was reshared', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_posts', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Channel Post',
                'verbose_name_plural': 'Channel Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='twitterstorm',
            index=models.Index(fields=['status'], name='campaigns_t_status_c91701_idx'),
        ),
        migrations.AddIndex(
            model_name='twitterstorm',
            index=models.Index(fields=['scheduled_at'], name='campaigns_t_schedul_91aaac_idx'),
        ),
        migrations.AddIndex(
            model_name='twitterstorm',
            index=models.Index(fields=['campaign', 'status'], name='campaigns_t_campaig_4e0f7d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stormparticipant',
            unique_together={('storm', 'volunteer')},
        ),
        migrations.AddIndex(
            model_name='channelpost',
            index=models.Index(fields=['campaign', 'content_type'], name='campaigns_c_campaig_39a2ea_idx'),
        ),
        migrations.AddIndex(
            model_name='channelpost',
            index=models.Index(fields=['campaign', 'last_reposted_at'], name='campaigns_c_campaig_cdba26_idx'),
        ),
    ]
