# Generated by Django 4.2.10 on 2026-04-12 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_add_pinned_dashboard_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('event_datetime', models.DateTimeField(blank=True, null=True)),
                ('topic', models.CharField(choices=[('anti_war', 'Anti-War'), ('palestine', 'Pro-Palestine'), ('lebanon', 'Pro-Lebanon'), ('iran', 'Pro-Iran'), ('peace', 'Pro-Peace'), ('other', 'Other')], default='other', max_length=30)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=True, help_text='If True, appears dynamically in the bot')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Protest Event',
                'verbose_name_plural': 'Protest Events',
                'ordering': ['-event_datetime'],
                'indexes': [models.Index(fields=['event_datetime', 'is_verified'], name='campaigns_p_event_d_79023e_idx')],
            },
        ),
    ]
