# Generated by Django 4.2.10 on 2026-03-05 07:48

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('campaign_manager', 'Campaign Manager'), ('volunteer', 'Volunteer')], default='volunteer', help_text='User role in the system', max_length=20)),
                ('telegram_id', models.BigIntegerField(blank=True, help_text='Telegram user ID for bot communication', null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram username (without @)', max_length=32, null=True)),
                ('telegram_chat_id', models.BigIntegerField(blank=True, help_text='Telegram chat ID for direct messaging', null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number for SMS notifications', max_length=20, null=True)),
                ('email_verified', models.BooleanField(default=False, help_text='Whether the email address has been verified')),
                ('phone_verified', models.BooleanField(default=False, help_text='Whether the phone number has been verified')),
                ('points', models.IntegerField(default=0, help_text='Points earned by completing tasks')),
                ('level', models.IntegerField(default=1, help_text='Volunteer level based on points')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'indexes': [models.Index(fields=['telegram_id'], name='users_user_telegra_b51e4c_idx'), models.Index(fields=['role'], name='users_user_role_36d76d_idx'), models.Index(fields=['points'], name='users_user_points_d9dafa_idx')],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
