#!/usr/bin/env python3
import os
from deep_translator import GoogleTranslator

target_dir = '/Users/mahdifarimani/Documents/PFP/PFP_Platform/web/public/media/subtitles/france24-what-we-know-minab-strike'
os.makedirs(target_dir, exist_ok=True)

# Exact 63 raw speech segments from Whisper with exact seconds
raw_segments = [
    (0.00, 9.52, "A mass funeral was held today for the 165 school children killed on Saturday in Iran,"),
    (9.52, 14.84, "the UN calling for a full investigation into a grave violation of humanitarian law."),
    (14.84, 20.56, "But online, some users are claiming that the incident was staged. Tell us more."),
    (20.56, 27.32, "Yes, exactly. With this user on X claiming that the school and the girls did not exist,"),
    (27.32, 31.90, "with this video that you can see playing behind me. According to this user, this footage"),
    (31.90, 38.12, "is war propaganda like the genocide and famine in Gaza. Some even turned to Grok,"),
    (38.12, 43.58, "that is the AI assistant embedded within the platform X, to fact-check the footage and"),
    (43.58, 49.12, "ask Grok if it's real. And Grok answered that the video is supposed to show an attack"),
    (49.12, 55.76, "on a school, yes, but in Kabul in 2021. So we tried to compare the footage"),
    (55.76, 60.96, "with former verified footage from the school attacked in 2021 in Kabul,"),
    (60.96, 67.44, "and as you can see, it's not the same building at all. Grok was simply wrong."),
    (67.44, 73.64, "And we tried to compare the actual viral footage with the maps that you can find"),
    (73.64, 78.52, "on Google Maps and Google Earth for example, or satellite imagery, and we"),
    (78.52, 84.32, "managed to identify the location as a girls' school in Minab — Shajareh Tayyebeh school in Minab."),
    (84.32, 92.04, "Iranian media reported that at least 165 deaths happened linked to the strike,"),
    (92.04, 96.88, "but that figure has not been independently verified. I have personally seen"),
    (96.88, 102.88, "a lot of verified footage showing the bodies of children beneath the rubble."),
    (102.88, 108.12, "Obviously, I'm not going to show you these videos that are very disturbing."),
    (108.12, 113.76, "You might have seen though one photo that was shared for example by the Iranian embassy in Vienna —"),
    (113.76, 118.68, "this photo right there. It is a blood-stained pink backpack,"),
    (118.68, 126.68, "but I've asked Gemini, this is an AI tool provided by Google, to check if it"),
    (126.68, 132.88, "managed to detect any invisible watermark, and the answer was yes:"),
    (132.88, 141.52, "this image was created or edited using AI tools by Google."),
    (141.52, 148.40, "So this suggests that even if we have real footage from the incident happening in Minab,"),
    (148.40, 156.08, "this specific photo was generated by AI. The strike itself is described as a war crime,"),
    (156.08, 161.36, "but online you found some people claiming that the building that was targeted may"),
    (161.36, 168.00, "not have been a purely civilian infrastructure. Exactly — any attack on anything civilian,"),
    (168.00, 173.68, "including a school for example, is generally a violation of international law,"),
    (173.68, 178.32, "unless you manage to prove there is credible evidence the building is used for something else."),
    (178.32, 184.72, "And that is what is alleged by this user who is saying that this building is located"),
    (184.72, 191.60, "within the same compound as several buildings belonging to the IRGC, Iran's Revolutionary Guard."),
    (191.60, 197.84, "These claims are based actually on open-source intelligence. Let's check together a map"),
    (197.84, 203.36, "from this platform, OpenStreetMap. This is a collaborative mapping platform where you can"),
    (203.36, 208.88, "mark many places, such as a school for example or military barracks, and that's"),
    (208.88, 214.48, "what happened here. Here is the location for the school, right here, and here you can see that"),
    (214.48, 220.72, "the rest is labeled as part of the Pasdaran barracks held by the Revolutionary Guards in Iran."),
    (220.80, 226.08, "And you can see that this site has been hit twice, and it's worth noting"),
    (226.08, 232.16, "that this area here is a clinic that was not hit."),
    (232.16, 239.44, "But the building that is currently a school has been hit. When you look at satellite imagery from 2013,"),
    (239.44, 245.12, "that would be the building here, you can see that it is clearly within the military compound."),
    (245.20, 250.40, "But if you look at more recent pictures from Google Earth and Google Maps,"),
    (250.40, 255.92, "you're going to see that there is now a wall, and this wall was built in 2016,"),
    (255.92, 263.28, "and this building was turned into an all-girls school in 2016. So it is separated from the military barracks,"),
    (263.28, 268.72, "and there is a separate independent entrance, and you also see these colorful walls,"),
    (269.52, 275.36, "and satellite imagery shows civilian infrastructure, such as playgrounds."),
    (275.36, 281.04, "So this is 100% civilian infrastructure according to satellite imagery."),
    (281.04, 286.40, "And finally, Maya, Tehran is blaming the US and Israel for this attack. Do we actually know who is responsible?"),
    (286.40, 292.00, "First, we have the Israeli military: They say they were not aware of any attack happening in the area."),
    (292.00, 297.28, "We have the Pentagon: The Pentagon says that it is currently investigating the incident."),
    (297.28, 303.04, "And we have US Secretary of State Marco Rubio, who was asked about it yesterday, and he said"),
    (303.04, 309.04, "that the US would not deliberately target a school, before adding that the Iranians, on the other hand,"),
    (309.04, 315.20, "according to him, are targeting civilian infrastructure, without adding any link to this school strike."),
    (315.20, 322.64, "Online, some users suggested that the school was targeted not by the US or Israel, but rather by Iran,"),
    (322.64, 331.20, "explaining that this was a failed rocket launch from the IRGC."),
    (331.20, 339.36, "But researchers managed to prove that the video shown as evidence to explain it was Iran"),
    (339.36, 345.04, "is actually showing another region in Iran: Zanjan —"),
    (345.04, 352.96, "that is 1,300 kilometers in the opposite direction from where the strike took place."),
    (352.96, 359.44, "So these are unrelated pictures showing a misfire elsewhere, not in Minab."),
    (359.44, 367.68, "And finally, there is another viral post seen 6 million times on X claiming Tehran admitted responsibility on Telegram."),
    (367.68, 374.08, "But if you look into this account, you will see very clearly that this Telegram account has no link to Iranian authorities."),
    (374.08, 379.68, "It is an opposition outlet well known for mixing information and satire."),
    (379.68, 385.12, "Thanks, Maya. Maya there with tonight's Truth or Fake."),
    (385.12, 388.48, "Do stay with us, we will be right back after this short break.")
]

def format_vtt_time(seconds):
    h = int(seconds // 3600)
    m = int((seconds % 3600) // 60)
    s = seconds % 60
    return f"{h:02d}:{m:02d}:{s:06.3f}"

translator_fa = GoogleTranslator(source='en', target='fa')
translator_fi = GoogleTranslator(source='en', target='fi')

en_vtt = ["WEBVTT\n"]
fa_vtt = ["WEBVTT\n"]
fi_vtt = ["WEBVTT\n"]

print(f"Translating and formatting all {len(raw_segments)} segments...")

for i, (start, end, en_text) in enumerate(raw_segments, 1):
    time_block = f"{format_vtt_time(start)} --> {format_vtt_time(end)}"
    
    try:
        fa_text = translator_fa.translate(en_text) or en_text
    except Exception as e:
        print(f"FA err: {e}")
        fa_text = en_text

    try:
        fi_text = translator_fi.translate(en_text) or en_text
    except Exception as e:
        print(f"FI err: {e}")
        fi_text = en_text

    en_vtt.append(f"\n{i}\n{time_block}\n{en_text}\n")
    fa_vtt.append(f"\n{i}\n{time_block}\n{fa_text}\n")
    fi_vtt.append(f"\n{i}\n{time_block}\n{fi_text}\n")

with open(os.path.join(target_dir, "en.vtt"), "w", encoding="utf-8") as f:
    f.writelines(en_vtt)

with open(os.path.join(target_dir, "fa.vtt"), "w", encoding="utf-8") as f:
    f.writelines(fa_vtt)

with open(os.path.join(target_dir, "fi.vtt"), "w", encoding="utf-8") as f:
    f.writelines(fi_vtt)

print("✅ Generated 63 perfectly synchronized cues across EN, FA, FI.")
