# Generated by Django 4.2.10 on 2026-03-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Task title', max_length=200)),
                ('description', models.TextField(help_text='Detailed task description')),
                ('instructions', models.TextField(help_text='Step-by-step instructions for volunteers')),
                ('task_type', models.CharField(choices=[('twitter_post', 'Twitter Post'), ('twitter_retweet', 'Twitter Retweet'), ('twitter_like', 'Twitter Like'), ('telegram_share', 'Telegram Share'), ('telegram_invite', 'Telegram Invite'), ('content_creation', 'Content Creation'), ('research', 'Research'), ('other', 'Other')], help_text='Type of task', max_length=50)),
                ('assignment_type', models.CharField(choices=[('first_come', 'First Come, First Served'), ('manual', 'Manual Assignment'), ('automatic', 'Automatic Assignment')], default='first_come', help_text='How tasks are assigned to volunteers', max_length=20)),
                ('points', models.IntegerField(default=10, help_text='Points awarded for completing this task')),
                ('estimated_time', models.IntegerField(default=15, help_text='Estimated time to complete in minutes')),
                ('max_assignments', models.IntegerField(default=1, help_text='Maximum number of volunteers who can complete this task')),
                ('current_assignments', models.IntegerField(default=0, help_text='Number of volunteers currently assigned')),
                ('completed_assignments', models.IntegerField(default=0, help_text='Number of volunteers who completed this task')),
                ('target_url', models.URLField(blank=True, help_text='URL for the task (e.g., tweet to retweet)')),
                ('hashtags', models.CharField(blank=True, help_text='Comma-separated list of hashtags', max_length=500)),
                ('mentions', models.CharField(blank=True, help_text='Comma-separated list of accounts to mention', max_length=500)),
                ('image_url', models.URLField(blank=True, help_text='URL of image to use (if applicable)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the task is available for assignment')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the task has been verified by a manager')),
                ('available_from', models.DateTimeField(blank=True, help_text='Date/time when task becomes available', null=True)),
                ('available_until', models.DateTimeField(blank=True, help_text='Date/time when task is no longer available', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='assigned', max_length=20)),
                ('proof_url', models.URLField(blank=True, help_text='URL proof of completion (e.g., tweet link)')),
                ('proof_text', models.TextField(blank=True, help_text='Text proof of completion')),
                ('proof_image', models.URLField(blank=True, help_text='Image proof of completion')),
                ('completion_notes', models.TextField(blank=True, help_text='Volunteer notes about completion')),
                ('verification_notes', models.TextField(blank=True, help_text='Manager notes about verification')),
                ('points_awarded', models.IntegerField(default=0, help_text='Points awarded for this assignment')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Task Assignment',
                'verbose_name_plural': 'Task Assignments',
            },
        ),
    ]
