# Generated by Django 4.2.10 on 2026-03-05 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('telegram', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telegrammessagelog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='telegram.telegramsession'),
        ),
        migrations.AddIndex(
            model_name='telegramsession',
            index=models.Index(fields=['telegram_id'], name='telegram_te_telegra_54de3a_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramsession',
            index=models.Index(fields=['state'], name='telegram_te_state_a81e18_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramsession',
            index=models.Index(fields=['last_interaction'], name='telegram_te_last_in_18a99e_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessagelog',
            index=models.Index(fields=['session', 'created_at'], name='telegram_te_session_4b8364_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrammessagelog',
            index=models.Index(fields=['created_at'], name='telegram_te_created_37f8bf_idx'),
        ),
    ]
