# Generated by Django 4.2.10 on 2026-03-05 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], help_text='Type of snapshot', max_length=50)),
                ('snapshot_date', models.DateField(help_text='Date the snapshot represents')),
                ('total_users', models.IntegerField(default=0)),
                ('new_users', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_campaigns', models.IntegerField(default=0)),
                ('active_campaigns', models.IntegerField(default=0)),
                ('completed_campaigns', models.IntegerField(default=0)),
                ('total_tasks', models.IntegerField(default=0)),
                ('completed_tasks', models.IntegerField(default=0)),
                ('verification_rate', models.FloatField(default=0)),
                ('total_points_awarded', models.IntegerField(default=0)),
                ('avg_points_per_user', models.FloatField(default=0)),
                ('avg_tasks_per_user', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-snapshot_date', 'snapshot_type'],
                'unique_together': {('snapshot_type', 'snapshot_date')},
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_register', 'User Register'), ('telegram_link', 'Telegram Link'), ('campaign_create', 'Campaign Create'), ('campaign_update', 'Campaign Update'), ('campaign_join', 'Campaign Join'), ('campaign_leave', 'Campaign Leave'), ('task_create', 'Task Create'), ('task_assign', 'Task Assign'), ('task_complete', 'Task Complete'), ('task_verify', 'Task Verify'), ('twitter_post', 'Twitter Post'), ('twitter_retweet', 'Twitter Retweet'), ('twitter_like', 'Twitter Like'), ('telegram_message', 'Telegram Message'), ('telegram_command', 'Telegram Command')], help_text='Type of action performed', max_length=50)),
                ('description', models.TextField(help_text='Human-readable description of the action')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
