# Generated by Django 4.2.10 on 2026-03-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramMessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(help_text='Telegram message ID')),
                ('chat_id', models.BigIntegerField(help_text='Telegram chat ID')),
                ('from_user', models.JSONField(help_text='User information from Telegram')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('command', 'Command'), ('callback_query', 'Callback Query'), ('photo', 'Photo'), ('document', 'Document')], help_text='Type of message', max_length=20)),
                ('content', models.TextField(help_text='Message content')),
                ('bot_response', models.TextField(blank=True, help_text='Bot response to this message', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telegram Message Log',
                'verbose_name_plural': 'Telegram Message Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(help_text='Telegram user ID', unique=True)),
                ('telegram_username', models.CharField(blank=True, help_text='Telegram username', max_length=32, null=True)),
                ('telegram_chat_id', models.BigIntegerField(help_text='Telegram chat ID for messaging')),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('awaiting_name', 'Awaiting Name'), ('awaiting_email', 'Awaiting Email'), ('awaiting_task_proof', 'Awaiting Task Proof'), ('awaiting_campaign_choice', 'Awaiting Campaign Choice'), ('awaiting_task_choice', 'Awaiting Task Choice'), ('awaiting_confirmation', 'Awaiting Confirmation')], default='idle', help_text='Current conversation state', max_length=50)),
                ('state_data', models.JSONField(default=dict, help_text='Data associated with current state')),
                ('temp_data', models.JSONField(default=dict, help_text='Temporary data storage for conversation flow')),
                ('last_interaction', models.DateTimeField(auto_now=True, help_text='Last interaction with the bot')),
                ('total_messages', models.IntegerField(default=0, help_text='Total messages exchanged')),
                ('commands_used', models.JSONField(default=dict, help_text='Count of commands used by this user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Session',
                'verbose_name_plural': 'Telegram Sessions',
            },
        ),
    ]
