"""
OTP-based authentication views for dashboard login.
Campaign managers authenticate via a code generated by the Telegram bot.
"""
from django.core.cache import cache
from rest_framework import serializers, status
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_simplejwt.tokens import RefreshToken

from ..models import User


class OTPLoginSerializer(serializers.Serializer):
    """Serializer for OTP login requests."""
    username = serializers.CharField(
        help_text='Telegram username (without @) or user_{telegram_id}'
    )
    otp_code = serializers.CharField(
        min_length=6, max_length=6,
        help_text='6-digit OTP code from Telegram bot'
    )


class OTPLoginView(APIView):
    """
    Authenticate via OTP code generated by the Telegram bot.

    POST /api/auth/otp-login/
    {
        "username": "Mfarimani",     // or "user_23932283"
        "otp_code": "123456"
    }
    """
    permission_classes = [AllowAny]

    def post(self, request):
        serializer = OTPLoginSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        username_input = serializer.validated_data['username'].strip()
        otp_code = serializer.validated_data['otp_code'].strip()

        # Look up user by telegram_username (case-insensitive) or username
        user = (
            User.objects.filter(telegram_username__iexact=username_input).first()
            or User.objects.filter(username__iexact=username_input).first()
        )

        if not user:
            return Response(
                {'error': 'User not found. Use your Telegram username or user ID.'},
                status=status.HTTP_401_UNAUTHORIZED
            )

        # Only admin and campaign_manager can log in
        if user.role not in ('admin', 'campaign_manager'):
            return Response(
                {'error': 'Dashboard access is restricted to campaign managers.'},
                status=status.HTTP_403_FORBIDDEN
            )

        # Verify OTP from Redis cache
        cache_key = f"otp:{user.telegram_id}"
        stored_otp = cache.get(cache_key)

        if not stored_otp:
            return Response(
                {'error': 'OTP expired or not found. Request a new code via /dashboard in the bot.'},
                status=status.HTTP_401_UNAUTHORIZED
            )

        if stored_otp.get('code') != otp_code:
            return Response(
                {'error': 'Invalid OTP code. Please check and try again.'},
                status=status.HTTP_401_UNAUTHORIZED
            )

        # OTP valid — delete it (one-time use)
        cache.delete(cache_key)

        # Issue JWT tokens
        refresh = RefreshToken.for_user(user)

        return Response({
            'access': str(refresh.access_token),
            'refresh': str(refresh),
            'user': {
                'id': user.pk,
                'username': user.username,
                'telegram_username': user.telegram_username,
                'first_name': user.first_name,
                'role': user.role,
            }
        })
